name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-22.04, ubuntu-24.04-arm]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Free Pascal
      run: |
        sudo apt update -y
        sudo apt install -y fpc

    - name: Compile Pascal code
      run: |
        make build

    - name: Compress binaries
      run: |
        tar -czf ite-hugo-utils-${{ runner.os }}-${{ runner.arch }}.tar.gz -C bin .
        
    - name: Create release
      if: success()
      uses: softprops/action-gh-release@v2
      with:
        files: *.tar.gz 

    - name: Upload release asset
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binaries
        path: *.tar.gz