name: CD

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Free Pascal
      run: |
        sudo apt update -y
        sudo apt install -y fpc

    - name: Compile Pascal code
      run: |
        make build

    - name: Compress binaries
      run: |
        tar -czf ite-hugo-utils.tar.gz -C bin .
        
    - name: Create release
      if: success()
      uses: softprops/action-gh-release@v2
      with:
        files: ite-hugo-utils.tar.gz 

    - name: Upload release asset
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binaries
        path: ite-hugo-utils.tar.gz