name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-22.04, ubuntu-24.04-arm]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Free Pascal
      run: |
        sudo apt update -y
        sudo apt install -y fpc

    - name: Compile Pascal code
      run: |
        make build

    - name: Compress binaries
      run: |
        tar -czf ite-hugo-utils-${{ runner.os }}-${{ runner.arch }}.tar.gz -C bin .
        
    - name: Create release
      if: success()
      uses: softprops/action-gh-release@v2
      with:
        files: ite-hugo-utils-${{ runner.os }}-${{ runner.arch }}.tar.gz

    - name: Upload release asset
      uses: actions/upload-artifact@v4
      with:
        name: ite-hugo-utils-${{ runner.os }}-${{ runner.arch }}
        path: ite-hugo-utils-${{ runner.os }}-${{ runner.arch }}.tar.gz

  macOS:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [macos-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Free Pascal
      run: |
        brew install fpc

    - name: Compile Pascal code
      run: |
        make build

    - name: Compress binaries
      run: |
        tar -czf ite-hugo-utils-${{ runner.os }}-${{ runner.arch }}.tar.gz -C bin .
        
    - name: Create release
      if: success()
      uses: softprops/action-gh-release@v2
      with:
        files: ite-hugo-utils-${{ runner.os }}-${{ runner.arch }}.tar.gz

    - name: Upload release asset
      uses: actions/upload-artifact@v4
      with:
        name: ite-hugo-utils-${{ runner.os }}-${{ runner.arch }}
        path: ite-hugo-utils-${{ runner.os }}-${{ runner.arch }}.tar.gz

  windows:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [windows-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Free Pascal
      run: |
        choco install freepascal -y
        choco install make -y

    - name: Add FreePascal to PATH
      run: echo "C:\\tools\\freepascal\\bin\\i386-Win32" >> $GITHUB_PATH

    - name: Compile Pascal code
      run: |
        $MAKEFILE_DIR = Get-Location

        $PAS_FILES = @(
            "./archive/bigfile/bigfileunpacker",
            "./archive/hugo5dos/unpackhugo5dat",
            "./archive/hugo4dos/unpackhugo4dat",
            "./archive/hugo_magick_oak/resdatunpack",
            "./archive/iteres/iteresunpack",
            "./archive/hugo3dos/unpack4hugo",
            "./archive/skaermtrolden_hugo_dat/pack",
            "./archive/skaermtrolden_hugo_dat/unpack2",
            "./archive/hugoxl/unpackmiscdat",
            "./archive/hugoxl/unpack_sbk",
            "./config/hugoxl/unpack_cfb",
            "./sync/oos/txt2oos",
            "./sync/oos/oos2txt",
            "./graphics/cbr/cbr2bmp",
            "./graphics/brs/brs2bmp",
            "./graphics/skaermtrolden_speach_cloud/decodespeach2",
            "./graphics/skaermtrolden_speach_cloud/encodespeach",
            "./graphics/lzp/lzp2bmp",
            "./graphics/cgf/cgf2bmp",
            "./graphics/til/til2bmp",
            "./graphics/pbr/pbr2bmp"
        )

        # Create the bin directory if it doesn't exist
        New-Item -ItemType Directory -Force -Path "$MAKEFILE_DIR\bin"

        foreach ($file in $PAS_FILES) {
            $dir = Split-Path $file
            Set-Location -Path $dir
            & "fpc" "-o$file" "$file.pas"
            Move-Item "$file" "$MAKEFILE_DIR\bin\"
        }

    - name: Compress binaries (ZIP)
      run: |
        7z a ite-hugo-utils-${{ runner.os }}-${{ runner.arch }}.zip bin\*

    - name: Create release
      if: success()
      uses: softprops/action-gh-release@v2
      with:
        files: ite-hugo-utils-${{ runner.os }}-${{ runner.arch }}.zip


    - name: Upload release asset
      uses: actions/upload-artifact@v4
      with:
        name: ite-hugo-utils-${{ runner.os }}-${{ runner.arch }}
        path: ite-hugo-utils-${{ runner.os }}-${{ runner.arch }}.zip
